### ISSUE TITLE
where can i download MANO_RIGHT.pkl ?

### ISSUE THREAD

**Issue by chouchunan** [hxwork/H2ONet_Pytorch#7]
(h2onet_py39) user@user-System-Product-Name:/media/user/test/H2ONet_Pytorch-main$ python test.py --model_dir=./experiment/multi_frame_dexycb/stage_2n --resume=./experiment/multi_frame_dexycb/stage_2/dexycb_h2onet_mf.pth
./common/utils/manopth/mano/models/MANO_RIGHT.pkl
Traceback (most recent call last):
  File "/media/user/test/H2ONet_Pytorch-main/test.py", line 6, in <module>
    from data_loader.data_loader import fetch_dataloader
  File "/media/user/test/H2ONet_Pytorch-main/data_loader/data_loader.py", line 8, in <module>
    from data_loader.DEX_YCB_SF import DEX_YCB_SF
  File "/media/user/test/H2ONet_Pytorch-main/data_loader/DEX_YCB_SF.py", line 11, in <module>
    mano = MANO()
  File "/media/user/test/H2ONet_Pytorch-main/common/utils/mano.py", line 9, in __init__
    self.layer = self.get_layer()
  File "/media/user/test/H2ONet_Pytorch-main/common/utils/mano.py", line 41, in get_layer
    return ManoLayer(mano_root=osp.join("./common/utils/manopth", "mano", "models"), flat_hand_mean=False, use_pca=False)  # load right hand MANO model
  File "/media/user/test/H2ONet_Pytorch-main/common/utils/manopth/manopth/manolayer.py", line 59, in __init__
    smpl_data = ready_arguments(self.mano_path)
  File "/media/user/test/H2ONet_Pytorch-main/common/utils/manopth/mano/webuser/smpl_handpca_wrapper_HAND_only.py", line 32, in ready_arguments
    dd = pickle.load(open(fname_or_dict, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: './common/utils/manopth/mano/models/MANO_RIGHT.pkl'

so where can i download MANO_RIGHT.pkl ?

**Comment by chouchunan** [comment]
solved
