### ISSUE TITLE
where can i download these two files in test.py ?

### ISSUE THREAD

**Issue by chouchunan** [hxwork/H2ONet_Pytorch#8]
template_fp = "model/h2onet/template/template.ply"
transform_fp = "model/h2onet/template/transform.pkl"

**Comment by hxwork** [comment]
These files can be generated by [this function](https://github.com/hxwork/H2ONet_Pytorch/blob/aee644e0eb6722e82bcbf62c0ce3cc4f31503826/model/modules/utils/read.py#L34).

**Comment by chouchunan** [comment]
(h2onet_py39) user@user-System-Product-Name:/media/user/test/H2ONet_Pytorch-main$ python test.py --model_dir=./experiment/multi_frame_dexycb/stage_2 --resume=./experiment/multi_frame_dexycb/stage_2/dexycb_h2onet_mf.pth
/media/user/test/H2ONet_Pytorch-main/common/utils/transforms.py:3: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 1.21.6)
  from scipy.linalg import orthogonal_procrustes
2024-06-18 21:28:44 root Output and logs will be saved to ./experiment/multi_frame_dexycb/stage_2/test.log
2024-06-18 21:28:44 root Using GPU ids: [0]
2024-06-18 21:28:44 data_loader.data_loader Dataset: DEX_YCB_MF
2024-06-18 21:28:44 data_loader.transforms Train transforms: ToTensor
2024-06-18 21:28:44 data_loader.transforms Val/Test transforms: ToTensor
loading annotations into memory...
Done (t=35.34s)
creating index...
index created!
loading annotations into memory...
Done (t=5.83s)
creating index...
index created!
/home/user/anaconda3/envs/h2onet_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 20 worker processes in total. Our suggested max number of worker in current system is 12, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
2024-06-18 21:30:02 model.modules.models.densestack Load pre-trained weight: densestack.pth
Generating transform matrices...
Traceback (most recent call last):
  File "/media/user/test/H2ONet_Pytorch-main/test.py", line 107, in <module>
    main(cfg)
  File "/media/user/test/H2ONet_Pytorch-main/test.py", line 81, in main
    model = fetch_model(cfg)
  File "/media/user/test/H2ONet_Pytorch-main/model/model.py", line 215, in fetch_model
    model = H2ONet_MF(cfg)
  File "/media/user/test/H2ONet_Pytorch-main/model/model.py", line 121, in __init__
    spiral_indices, _, up_transform, tmp = spiral_tramsform(transform_fp, template_fp, ds_factors=[2, 2, 2, 2], seq_length=[9, 9, 9, 9], dilation=[1, 1, 1, 1])
  File "/media/user/test/H2ONet_Pytorch-main/model/modules/utils/read.py", line 37, in spiral_tramsform
    mesh = Mesh(filename=template_fp)
  File "/home/user/anaconda3/envs/h2onet_py39/lib/python3.9/site-packages/psbody/mesh/mesh.py", line 67, in __init__
    self.load_from_file(filename)
  File "/home/user/anaconda3/envs/h2onet_py39/lib/python3.9/site-packages/psbody/mesh/mesh.py", line 461, in load_from_file
    serialization.load_from_file(self, filename)
  File "/home/user/anaconda3/envs/h2onet_py39/lib/python3.9/site-packages/psbody/mesh/serialization/serialization.py", line 412, in load_from_file
    self.load_from_ply(filename)
  File "/home/user/anaconda3/envs/h2onet_py39/lib/python3.9/site-packages/psbody/mesh/mesh.py", line 464, in load_from_ply
    serialization.load_from_ply(self, filename)
  File "/home/user/anaconda3/envs/h2onet_py39/lib/python3.9/site-packages/psbody/mesh/serialization/serialization.py", line 431, in load_from_ply
    from psbody.mesh.serialization import plyutils
ImportError: cannot import name 'plyutils' from 'psbody.mesh.serialization' (/home/user/anaconda3/envs/h2onet_py39/lib/python3.9/site-packages/psbody/mesh/serialization/__init__.py)


how can i solve this problem? thanks

**Comment by Mine268** [comment]
我在相关工作下面找了一下，找到了transform.pkl和template.ply文件
[https://github.com/SeanChenxy/HandMesh/tree/main/template](https://github.com/SeanChenxy/HandMesh/tree/main/template)

**Comment by Skullface9512** [comment]
@chouchunan hi, i have some problems in loading weight

```
2025-03-05 18:56:16 root Output and logs will be saved to /media/goertek/5f79ed5e-a5cd-4fdc-8223-2f15a0baa8c5/goertek/workspace/H2ONet_Pytorch-main/experiment/multi_frame_ho3d/stage_2/test.log
2025-03-05 18:56:16 root Using GPU ids: [0]
2025-03-05 18:56:16 data_loader.data_loader Dataset: HO3D_MF
2025-03-05 18:56:16 data_loader.transforms Train transforms: ToTensor
2025-03-05 18:56:16 data_loader.transforms Val/Test transforms: ToTensor
loading annotations into memory...
Done (t=4.75s)
creating index...
index created!
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
Traceback (most recent call last):
  File "/media/goertek/5f79ed5e-a5cd-4fdc-8223-2f15a0baa8c5/goertek/workspace/H2ONet_Pytorch-main/test.py", line 107, in <module>
    main(cfg)
  File "/media/goertek/5f79ed5e-a5cd-4fdc-8223-2f15a0baa8c5/goertek/workspace/H2ONet_Pytorch-main/test.py", line 81, in main
    model = fetch_model(cfg)
  File "/media/goertek/5f79ed5e-a5cd-4fdc-8223-2f15a0baa8c5/goertek/workspace/H2ONet_Pytorch-main/model/model.py", line 215, in fetch_model
    model = H2ONet_MF(cfg)
  File "/media/goertek/5f79ed5e-a5cd-4fdc-8223-2f15a0baa8c5/goertek/workspace/H2ONet_Pytorch-main/model/model.py", line 118, in __init__
    self.backbone = H2ONet_Backnone(cfg=self.cfg, latent_size=latent_size, kpts_num=21)
  File "/media/goertek/5f79ed5e-a5cd-4fdc-8223-2f15a0baa8c5/goertek/workspace/H2ONet_Pytorch-main/model/modules/models/densestack.py", line 251, in __init__
    weight = torch.load("/media/goertek/5f79ed5e-a5cd-4fdc-8223-2f15a0baa8c5/goertek/"
  File "/home/goertek/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/goertek/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

```

Do you know this reason, thank you.

**Comment by Skullface9512** [comment]
I have solves this problem @chouchunan
